# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [1]:
# Import torch
import torch

# Create random tensor
tensor = torch.rand(7, 7)

print(tensor)

tensor([[0.0269, 0.5370, 0.4770, 0.7550, 0.3264, 0.3689, 0.5199],
        [0.9823, 0.2207, 0.1903, 0.4795, 0.4930, 0.4543, 0.5325],
        [0.8620, 0.8124, 0.4678, 0.7563, 0.7612, 0.1192, 0.8650],
        [0.5111, 0.4646, 0.7277, 0.2780, 0.4201, 0.8818, 0.9254],
        [0.5895, 0.7766, 0.6362, 0.5168, 0.3093, 0.6834, 0.9685],
        [0.0282, 0.5844, 0.9773, 0.3723, 0.0981, 0.7979, 0.0476],
        [0.0618, 0.7618, 0.8485, 0.4684, 0.1576, 0.1852, 0.4949]])


### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [2]:
# Create another random tensor
tensor2 = torch.rand(1, 7)

# Perform matrix multiplication
result = torch.matmul(tensor, tensor2.T)

print(result)

tensor([[1.3423],
        [1.3595],
        [1.8040],
        [1.9662],
        [2.0642],
        [1.7512],
        [1.3563]])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [3]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
tensor1 = torch.rand(7, 7)
tensor2 = torch.rand(1, 7)

# Matrix multiply tensors
result = torch.matmul(tensor1, tensor2.T)

print(result, result.shape)


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]]) torch.Size([7, 1])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [4]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [5]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
tensorA = torch.rand(2, 3, device=device)
tensorB = torch.rand(2, 3, device=device)

print(tensorA, tensorB)


Device: cpu
tensor([[0.0290, 0.4019, 0.2598],
        [0.3666, 0.0583, 0.7006]]) tensor([[0.0518, 0.4681, 0.6738],
        [0.3315, 0.7837, 0.5631]])



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [6]:
# Perform matmul on tensor_A and tensor_B
result = torch.matmul(tensorA, tensorB.T)

print(result, result.shape)


tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]]) torch.Size([2, 2])


### 8. Find the maximum and minimum values of the output of 7.

In [7]:
# Find max
max_value = torch.max(result)

# Find min
min_value = torch.min(result)

print(max_value, min_value)


tensor(0.5617) tensor(0.3647)


### 9. Find the maximum and minimum index values of the output of 7.

In [8]:
# Find arg max
max_index = torch.argmax(result)

# Find arg min
min_index = torch.argmin(result)

print(max_index, min_index)


tensor(3) tensor(0)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [9]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed = tensor.squeeze()

# Print out tensors and their shapes
print(tensor, tensor.shape)
print(squeezed, squeezed.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])


###  My Named Is : Mohamed Ebrahim Hamed 